import Head from 'next/head'
import Hero from '@/src/components/home/hero'
import Divisoria from '@/src/components/home/divisoria'
import Lancamento from '@/src/components/home/lancamento'
import Barra from '@/src/components/home/barra'
import Footer from '@/src/components/home/footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Mainstreet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main>
        <Hero/>
        <Divisoria/>
        <Lancamento/>
        <Barra/>
        <Footer/>
        
      </main>
    </>
  )
}
